name: Docker deployment

on:
    push:
        branches:
            - main
            
    workflow_dispatch:

jobs:
  docker-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest

      - name: Print pwd
        run: echo "$(pwd)"

      - run: ls
      - run: cat docker-compose.yml


      - name: Start the deployment
        run: sudo docker compose up -d

      - name: See all the containers
        run: |
            sudo docker images
            sudo docker ps




      
