name: Docker deployment

on:
    push:
        branches:
            - main
            
    workflow_dispatch:

jobs:
  docker-setup:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest

      - name: Print pwd
        run: echo "$(pwd)"

      - run: ls
      - run: cat docker-compose.yml
      - name: remove all container
        run : sudo docker rm $(docker ps -aq)

      - name: remove the image
        run: sudo docker rmi -f $(docker images -aq)


      - name: Start the deployment
        run: sudo docker compose up -d

      - name: See all the containers
        run: |
            sudo docker images
            sudo docker ps
      - name: Ip address
        run: ip addr






      
